"""Run the local persistence and migration gate without external credentials.

This check does not connect to PostgreSQL or Supabase. It verifies the checked-in
PostgreSQL migration contains the observation contract, then exercises the local
SQLite contract with an insert, an idempotent replay, and a linked revision.
Remote schema execution, Data API exposure, backups, and restore tests still
require the corresponding provider-side checks.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from uuid import uuid4

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from src.data import Observation, SQLiteObservationStore

SCHEMA_PATH = (
    REPOSITORY_ROOT / "supabase" / "migrations" / "20260917000100_observations.sql"
)
MARKET_SCORE_SCHEMA_PATH = (
    REPOSITORY_ROOT / "supabase" / "migrations" / "20260917000200_market_scores.sql"
)

REQUIRED_SCHEMA_MARKERS = (
    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    "supersedes_id BIGINT REFERENCES observations(id)",
    "source_payload_hash TEXT NOT NULL",
    "values_json JSONB NOT NULL",
    "retrieval_count INTEGER NOT NULL DEFAULT 1 CHECK (retrieval_count >= 1)",
    "CREATE UNIQUE INDEX IF NOT EXISTS observations_payload_identity",
    "CREATE INDEX IF NOT EXISTS observations_logical_identity",
)

REQUIRED_MARKET_SCORE_SCHEMA_MARKERS = (
    "CREATE TABLE IF NOT EXISTS public.market_scores",
    "market_scores_value_state",
    "market_scores_calculation_identity",
    "CREATE INDEX IF NOT EXISTS market_scores_latest_date",
    "ALTER TABLE public.market_scores ENABLE ROW LEVEL SECURITY",
)


def _make_observation(**changes: object) -> Observation:
    fields: dict[str, object] = {
        "dataset_id": "twse_taiex_daily_v1",
        "schema_version": "0.1",
        "observation_date": "2026-09-15",
        "source_date": "2026-09-15",
        "source_name": "TWSE",
        "source_url": "https://example.test/taiex",
        "source_record_key": "TAIEX",
        "retrieved_at": "2026-09-16T00:00:00+00:00",
        "ingested_at": "2026-09-16T00:01:00+00:00",
        "source_payload_hash": "1" * 64,
        "parser_version": "persistence-gate@1",
        "values": {"close": 22_000.5, "unit": "index_points"},
        "quality_status": "available",
    }
    fields.update(changes)
    return Observation(**fields)


def check_postgres_migration(schema_path: Path = SCHEMA_PATH) -> None:
    """Check that the checked-in migration preserves the storage contract."""
    sql = schema_path.read_text(encoding="utf-8")
    normalized = re.sub(r"\s+", " ", sql).strip()
    missing = [marker for marker in REQUIRED_SCHEMA_MARKERS if marker not in normalized]
    if missing:
        raise AssertionError(
            "PostgreSQL migration is missing required contract markers: "
            + ", ".join(missing)
        )


def check_market_score_migration(
    schema_path: Path = MARKET_SCORE_SCHEMA_PATH,
) -> None:
    """Check that the market-score migration is present and contract-complete."""
    sql = schema_path.read_text(encoding="utf-8")
    normalized = re.sub(r"\s+", " ", sql).strip()
    missing = [
        marker
        for marker in REQUIRED_MARKET_SCORE_SCHEMA_MARKERS
        if marker not in normalized
    ]
    if missing:
        raise AssertionError(
            "Market-score migration is missing required contract markers: "
            + ", ".join(missing)
        )


def run_local_smoke_test() -> None:
    """Exercise idempotency and revision lineage using a temporary SQLite DB."""
    db_path = REPOSITORY_ROOT / f".persistence-gate-{uuid4().hex}.sqlite3"
    try:
        with SQLiteObservationStore(db_path) as store:
            first = store.write_observation(_make_observation())
            duplicate = store.write_observation(
                _make_observation(retrieved_at="2026-09-16T00:02:00+00:00")
            )
            revised = store.write_observation(
                _make_observation(
                    values={"close": 22_001.5, "unit": "index_points"},
                    source_payload_hash="2" * 64,
                    supersedes_id=first.observation_id,
                )
            )

            if first.action != "inserted":
                raise AssertionError("first observation was not inserted")
            if (
                duplicate.action != "duplicate"
                or duplicate.observation_id != first.observation_id
            ):
                raise AssertionError("same payload replay was not idempotent")
            if (
                revised.action != "inserted"
                or revised.observation_id == first.observation_id
            ):
                raise AssertionError("revised payload did not append a new row")

            rows = store._connection.execute(
                """
                SELECT id, dataset_id, observation_date, source_record_key,
                       publication_label, source_payload_hash, supersedes_id,
                       retrieval_count
                FROM observations
                ORDER BY id
                """
            ).fetchall()
            if len(rows) != 2:
                raise AssertionError(
                    f"expected 2 observations after replay, got {len(rows)}"
                )
            if rows[0]["retrieval_count"] != 2:
                raise AssertionError(
                    "duplicate replay did not increment retrieval_count"
                )
            expected_identity = (
                "twse_taiex_daily_v1",
                "2026-09-15",
                "TAIEX",
                None,
            )
            for row in rows:
                identity = tuple(
                    row[field]
                    for field in (
                        "dataset_id",
                        "observation_date",
                        "source_record_key",
                        "publication_label",
                    )
                )
                if identity != expected_identity:
                    raise AssertionError("observation logical identity changed")
            if rows[0]["source_payload_hash"] != "1" * 64:
                raise AssertionError("original payload hash was not preserved")
            if rows[1]["source_payload_hash"] != "2" * 64:
                raise AssertionError("revision payload hash was not preserved")
            if rows[1]["supersedes_id"] != rows[0]["id"]:
                raise AssertionError("revision does not point to its predecessor")
            if store.get_observation(rows[0]["id"]).values != {
                "close": 22_000.5,
                "unit": "index_points",
            }:
                raise AssertionError("revision replay changed the original payload")
    finally:
        db_path.unlink(missing_ok=True)


def main() -> None:
    check_postgres_migration()
    check_market_score_migration()
    run_local_smoke_test()
    print(
        "Local persistence gate passed: migration contract and SQLite replay/lineage checks."
    )
    print("No network requests or credentials were used.")


if __name__ == "__main__":
    main()
