CREATE TABLE IF NOT EXISTS observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id TEXT NOT NULL,
    schema_version TEXT NOT NULL,
    observation_date TEXT NOT NULL,
    source_date TEXT NOT NULL,
    source_name TEXT NOT NULL,
    source_url TEXT NOT NULL,
    source_record_key TEXT NOT NULL,
    published_at TEXT,
    publication_label TEXT,
    effective_at TEXT,
    retrieved_at TEXT NOT NULL,
    last_retrieved_at TEXT NOT NULL,
    ingested_at TEXT NOT NULL,
    source_revision TEXT,
    supersedes_id BIGINT REFERENCES observations(id),
    source_payload_hash TEXT NOT NULL,
    parser_version TEXT NOT NULL,
    values_json JSONB NOT NULL,
    quality_status TEXT NOT NULL,
    quality_notes TEXT,
    retrieval_count INTEGER NOT NULL DEFAULT 1 CHECK (retrieval_count >= 1),
    created_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS observations_payload_identity
ON observations (
    dataset_id,
    observation_date,
    source_record_key,
    COALESCE(publication_label, ''),
    COALESCE(source_revision, ''),
    source_payload_hash
);

CREATE INDEX IF NOT EXISTS observations_logical_identity
ON observations (
    dataset_id,
    observation_date,
    source_record_key,
    COALESCE(publication_label, ''),
    COALESCE(source_revision, ''),
    id
);
